package user.form;

import net.miginfocom.swing.MigLayout;

import java.util.List;

import user.component.Chat_Body;
import user.component.Chat_Bottom;
import user.component.Chat_Title;
import user.event.EventChat;
import user.event.PublicEvent;

import user.model.Model_Receive_Message;
import user.model.Model_Send_Message;
import user.model.Model_Group_Chat;
import user.model.Model_User_Account;

public class Chat extends javax.swing.JPanel {
    public Chat() {
        initComponents();
        init();
    }

    private void init() {
        setLayout(new MigLayout("fillx", "0[fill]0", "0[]0[100%, fill]0[shrink 0]0"));
        PublicEvent.getInstance().addEventChat(new EventChat() {
            @Override
            public void sendMessage(Model_Send_Message data) {
                chatBody.addItemRight(data);
            }

            @Override
            public void receiveMessage(Model_Receive_Message data) {
                if (chat_Title1.getChat().getGroupId() == data.getGroupID()) {
                    chatBody.addItemLeft(data);
                }
            }
        });
        add(chat_Title1, "wrap");
        add(chatBody, "wrap");
        add(chatBottom, "h ::50%");
    }

    public void setChat(Model_Group_Chat groupChat) {
        chat_Title1.setChatName(groupChat);
        chatBottom.setChat(groupChat);
        chatBody.clearChat();
    }

    public void updateUser(Model_Group_Chat groupChat) {
        chat_Title1.updateUser(groupChat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        chat_Title1 = new Chat_Title();
        chatBody = new Chat_Body();
        chatBottom = new Chat_Bottom();
        
        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 727, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
        );

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private user.component.Chat_Body chatBody;
    private user.component.Chat_Bottom chatBottom;
    private user.component.Chat_Title chat_Title1;
    // End of variables declaration//GEN-END:variables
}