/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package admin;

/**
 *
 * @author Nghiax
 */
public class adminHomePagePanel extends javax.swing.JPanel {

    /**
     * Creates new form adminHomePagePanel
     */
    public adminHomePagePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spamReports1 = new admin.components.spamReports();
        newUserRegistration1 = new admin.components.newUserRegistration();
        adminHomePage = new javax.swing.JTabbedPane();
        userDetail1 = new admin.components.userDetail();
        loginHistory1 = new admin.components.loginHistory();
        groupList1 = new admin.components.groupList();
        spamReports2 = new admin.components.spamReports();
        newUserRegistration2 = new admin.components.newUserRegistration();
        friendCount1 = new admin.components.friendCount();
        activeList1 = new admin.components.activeList();

        adminHomePage.addTab("User Details", userDetail1);
        adminHomePage.addTab("Login History", loginHistory1);
        adminHomePage.addTab("Group List", groupList1);
        adminHomePage.addTab("Spam Reports", spamReports2);
        adminHomePage.addTab("New User Registration", newUserRegistration2);
        adminHomePage.addTab("Friend Count", friendCount1);
        adminHomePage.addTab("Active List", activeList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminHomePage, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminHomePage)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private admin.components.activeList activeList1;
    private javax.swing.JTabbedPane adminHomePage;
    private admin.components.friendCount friendCount1;
    private admin.components.groupList groupList1;
    private admin.components.loginHistory loginHistory1;
    private admin.components.newUserRegistration newUserRegistration1;
    private admin.components.newUserRegistration newUserRegistration2;
    private admin.components.spamReports spamReports1;
    private admin.components.spamReports spamReports2;
    private admin.components.userDetail userDetail1;
    // End of variables declaration//GEN-END:variables
}
