/*
 * This source file was generated by the Gradle 'init' task
 */
package user;

import user.loginUI.*;

public class App {
    public static void main(String[] args) {
        // Login
        Login.main(args);
    }
}
